import numpy as np
from . import cwignerd


class GaussLegendreQuadrature:
    """Gauss-Legendre quadrature helper for Wigner-d transforms.

    The quadrature nodes and weights are generated by the compiled Wigner-d
    backend, based on routines from ``libkms_ist`` by Kendrick Smith.

    Attributes
    ----------
    npoints : int
        Number of quadrature points.
    zvec : numpy.ndarray
        Quadrature nodes in ``[-1, 1]``.
    wvec : numpy.ndarray
        Integration weights for each node.
    """

    def __init__(self, npoints):
        """Initialize quadrature nodes and weights.

        Parameters
        ----------
        npoints : int
            Number of Gauss-Legendre quadrature points.
        """
        self.npoints = npoints
        self.zvec, self.wvec = cwignerd.init_gauss_legendre_quadrature(npoints)

    def cf_from_cl(self, s1, s2, cl):
        r"""Evaluate a correlation function from harmonic coefficients.

        Computes

        .. math::

            \xi_j = \sum_l C_l d^l_{s_1 s_2}(z_j),

        where ``z_j`` are this object's quadrature nodes.

        Parameters
        ----------
        s1, s2 : int
            Spin indices of the Wigner-d matrix.
        cl : array_like
            Harmonic coefficients with shape ``(lmax + 1,)``. Complex inputs
            are supported by transforming real and imaginary parts separately.

        Returns
        -------
        numpy.ndarray
            Correlation-function samples at the quadrature nodes.
        """
        lmax = len(cl) - 1

        if np.iscomplexobj(cl):
            cl2d = np.concatenate([cl.real, cl.imag])
            output = cwignerd.wignerd_cf_from_cl(s1, s2, 2, self.npoints, lmax, self.zvec, cl2d).reshape(
                2, -1
            )
            return output[0] + 1j * output[1]

        else:
            return cwignerd.wignerd_cf_from_cl(s1, s2, 1, self.npoints, lmax, self.zvec, cl)

    def cl_from_cf(self, lmax, s1, s2, cf):
        r"""Project correlation-function samples onto harmonic coefficients.

        Computes the Gauss-Legendre approximation to

        .. math::

            C_l = \int_{-1}^{1} \xi(z) d^l_{s_1 s_2}(z)\,dz
                \simeq \sum_j w_j \xi_j d^l_{s_1 s_2}(z_j).

        Parameters
        ----------
        lmax : int
            Maximum multipole of the returned coefficients.
        s1, s2 : int
            Spin indices of the Wigner-d matrix.
        cf : array_like
            Correlation-function samples at this object's quadrature nodes.
            Complex inputs are supported by transforming real and imaginary
            parts separately.

        Returns
        -------
        numpy.ndarray
            Harmonic coefficients with shape ``(lmax + 1,)``.
        """
        if np.iscomplexobj(cf):
            cf2d = np.concatenate([cf.real, cf.imag])
            output = cwignerd.wignerd_cl_from_cf(
                s1, s2, 2, self.npoints, lmax, self.zvec, self.wvec, cf2d
            ).reshape(2, -1)
            return output[0] + 1j * output[1]
        else:
            return cwignerd.wignerd_cl_from_cf(s1, s2, 1, self.npoints, lmax, self.zvec, self.wvec, cf)


def get_product_spectra(cl, clw, lmax=None):
    """Compute product spectra using correlation-function methods with Gauss-Legendre quadrature.

    This uses the Wigner-d correlation-function method. For a scalar field
    ``X`` and scalar window ``W``, the output is the spectrum of ``X * W``.
    For polarization input, ``cl`` is interpreted as ``[EE, BB]`` and the
    returned array contains the windowed ``[EE, BB]`` spectra.

    Notes
    -----
    For scalar random fields ``X`` and ``W`` with spectra ``C_l^X`` and
    ``C_l^W``, the product spectrum can be written as a Wigner-3j convolution.
    This routine evaluates the same convolution through Wigner-d transforms,
    which is typically faster for the use cases in this package.

    Parameters
    ----------
    cl : numpy.ndarray
        Input spectrum with shape ``(lmax + 1,)`` for scalar fields or
        ``(2, lmax + 1)`` for ``[EE, BB]`` polarization spectra.
    clw : numpy.ndarray
        Scalar window spectrum with shape ``(lmax_w + 1,)``.
    lmax : int, optional
        Maximum multipole of the output. If omitted, uses the maximum multipole
        of ``cl``.

    Returns
    -------
    numpy.ndarray
        Product spectrum with shape ``(lmax + 1,)`` for scalar input or
        ``(2, lmax + 1)`` for polarization input.
    """
    _lmax = cl.shape[-1] - 1
    lmax_w = clw.shape[-1] - 1
    if lmax is None:
        lmax = _lmax
    npoints = (_lmax + lmax_w + lmax) // 2 + 1
    glq = GaussLegendreQuadrature(npoints)

    def _f(n):
        return (2 * np.arange(n + 1) + 1) / (4 * np.pi)

    xi_W = glq.cf_from_cl(0, 0, _f(lmax_w) * clw)  # compute once
    if cl.ndim == 2 and cl.shape[0] == 2:
        clp = cl[0] + cl[1]
        clm = cl[0] - cl[1]
        xi_p = glq.cf_from_cl(2, 2, _f(_lmax) * clp)
        xi_m = glq.cf_from_cl(2, -2, _f(_lmax) * clm)
        out_p = 2 * np.pi * glq.cl_from_cf(lmax, 2, 2, xi_p * xi_W)
        out_m = 2 * np.pi * glq.cl_from_cf(lmax, 2, -2, xi_m * xi_W)
        out = np.array([(out_p + out_m) / 2, (out_p - out_m) / 2])
    elif cl.ndim == 1 or cl.shape[0] == 1:
        xi_X = glq.cf_from_cl(0, 0, _f(_lmax) * cl)
        out = 2 * np.pi * glq.cl_from_cf(lmax, 0, 0, xi_X * xi_W)
    else:
        raise ValueError(f"cl must be either 1d or 2d with shape (2, lmax+1), got {cl.shape}")
    return out


def get_product_spectra_camb(cl1, cl2, lmax=None):
    """Compute product spectra with CAMB's harmonic-space coupling matrix.

    This is an independent harmonic-space implementation of
    :func:`get_product_spectra`, intended mainly as a validation check for the
    faster Wigner-d correlation-function method.

    Notes
    -----
    This routine requires ``camb`` at runtime. It is much slower than
    :func:`get_product_spectra`. In existing comparisons, the TT, EE, and BB
    auto terms agree well, while the EE-to-BB and BB-to-EE leakage terms can
    differ at the few-percent level at low-ell.

    Parameters
    ----------
    cl1 : numpy.ndarray
        Polarization spectra with shape ``(2, lmax1 + 1)`` for ``[EE, BB]``.
    cl2 : numpy.ndarray
        Scalar window spectrum with shape ``(lmax2 + 1,)``.
    lmax : int, optional
        Maximum multipole of the output. If omitted, uses
        ``min(lmax1, lmax2)``.

    Returns
    -------
    numpy.ndarray
        Product polarization spectra with shape ``(2, lmax + 1)``.
    """
    from camb import threej_coupling

    lmax1 = cl1.shape[-1] - 1
    lmax2 = cl2.shape[-1] - 1
    if lmax is None:
        lmax = min(lmax1, lmax2)
    l1 = np.arange(lmax1 + 1)
    l2 = np.arange(lmax2 + 1)
    W = (2 * l2 + 1) * cl2 / 4 / np.pi
    Ztt, _, Zee, Zeb = threej_coupling(W, lmax=cl2.shape[-1] - 1, pol=True)
    clee = Zee @ ((2 * l1 + 1) * cl1[0]) + Zeb @ ((2 * l1 + 1) * cl1[1])
    clbb = Zeb @ ((2 * l1 + 1) * cl1[0]) + Zee @ ((2 * l1 + 1) * cl1[1])
    return np.array([clee, clbb])[:, : lmax + 1]
